import type { Prompt } from '../types/prompt';

export const INITIAL_SAMPLE_PROMPTS: Prompt[] = [
  {
    id: 'sample-1',
    title: 'Senior Code Reviewer & Security Auditor',
    prompt: `Act as a Senior Principal Software Engineer and Security Specialist. Review the following code snippet for logic flaws, race conditions, memory leaks, performance bottlenecks, and security vulnerabilities (OWASP Top 10). Provide refactored code with explanatory diffs.\n\nCode to review:\n\`\`\`typescript\n// Paste code here\n\`\`\``,
    category: 'Coding',
    tags: ['code-review', 'security', 'typescript', 'refactoring'],
    description: 'Comprehensive code review prompt focusing on software architecture, security, and performance.',
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    isFavorite: true,
    isPinned: true,
    order: 0,
  },
  {
    id: 'sample-2',
    title: 'SaaS Value Proposition & Tagline Generator',
    prompt: `You are an elite B2B SaaS Brand Strategist. Analyze the following target audience and product features. Generate 5 unique brand positioning statements, 10 catchy landing page taglines, and a 30-second elevator pitch.\n\nProduct Details:\n[Insert features & target customer details]`,
    category: 'Marketing',
    tags: ['branding', 'saas', 'copywriting', 'positioning'],
    description: 'Generates compelling taglines and value propositions for tech products.',
    createdAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
    isFavorite: true,
    isPinned: true,
    order: 1,
  },
  {
    id: 'sample-3',
    title: 'SEO Long-Form Tech Blog Outline & Hook',
    prompt: `Act as an expert Content Marketer and SEO Strategist. Create a detailed 2,500-word blog post outline on the topic below. Include H2/H3 heading hierarchy, target keywords to integrate, compelling opening hooks, and key takeaways.\n\nTopic:\n[Insert blog topic]`,
    category: 'Content Writing',
    tags: ['seo', 'blogging', 'outline', 'content-marketing'],
    description: 'Structured SEO blog outline generator designed for high organic search rankings.',
    createdAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
    isFavorite: false,
    isPinned: false,
    order: 2,
  },
  {
    id: 'sample-4',
    title: 'Cold Outreach & Enterprise Pitch Email',
    prompt: `Draft a high-converting cold email to a VP of Engineering introducing a developer tool. Keep it under 125 words, emphasize a single key pain point (slow build times), include a soft call-to-action (15-min chat), and write 3 subject line options.`,
    category: 'Email',
    tags: ['sales', 'cold-email', 'outreach', 'b2b'],
    description: 'High-converting sales outreach email template designed for high response rates.',
    createdAt: new Date(Date.now() - 86400000 * 2.5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2.5).toISOString(),
    isFavorite: true,
    isPinned: false,
    order: 3,
  },
  {
    id: 'sample-5',
    title: 'Executive Resume Accomplishment Quantifier',
    prompt: `Transform the following bullet points into high-impact, quantified resume achievements using the Google X-Y-Z formula ("Accomplished [X] as measured by [Y], by doing [Z]").\n\nOriginal Bullets:\n[Insert experience bullet points]`,
    category: 'Resume',
    tags: ['resume', 'career', 'interview-prep', 'xyz-formula'],
    description: 'Re-writes resume bullet points into data-driven accomplishments.',
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    isFavorite: false,
    isPinned: false,
    order: 4,
  },
  {
    id: 'sample-6',
    title: 'Complex SQL Query Builder & Optimizer',
    prompt: `You are a Database Administrator specializing in PostgreSQL and MySQL optimization. Write an optimized SQL query for the following scenario, and explain indexing strategies to improve execution time.\n\nRequirements:\n[Insert query requirement and schema]`,
    category: 'SQL',
    tags: ['sql', 'database', 'optimization', 'postgresql'],
    description: 'Generates efficient SQL queries with query plan explanations and index suggestions.',
    createdAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1.5).toISOString(),
    isFavorite: true,
    isPinned: false,
    order: 5,
  },
  {
    id: 'sample-7',
    title: 'Design System Component Spec & Token Guide',
    prompt: `Act as a Lead UI/UX Designer. Create a comprehensive design spec for a multi-variant Button component. Define color tokens (idle, hover, active, disabled in hex/HSL), typography scales, padding, border-radius, and accessibility contrast requirements (WCAG AAA).`,
    category: 'Design',
    tags: ['ui-ux', 'design-system', 'tokens', 'accessibility'],
    description: 'Creates design specifications and tokens for modern UI component libraries.',
    createdAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
    isFavorite: false,
    isPinned: false,
    order: 6,
  },
  {
    id: 'sample-8',
    title: 'Viral LinkedIn Tech Post Carousel Strategy',
    prompt: `Write an engaging LinkedIn post about lessons learned building scalable distributed systems. Use hook-line-sinker structure, line breaks for readability, key takeaways as bullet points, and ending call-to-action for comments.`,
    category: 'Social Media',
    tags: ['linkedin', 'personal-brand', 'growth', 'tech-writing'],
    description: 'Crafts viral LinkedIn posts and carousels for tech professionals.',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
    isFavorite: false,
    isPinned: false,
    order: 7,
  },
  {
    id: 'sample-9',
    title: 'Weekly Eisenhower Matrix & Priority Planner',
    prompt: `Categorize the following master list of tasks into the Eisenhower Matrix (Do First, Schedule, Delegate, Eliminate). Recommend optimal time blocks (Pomodoro / Deep Work) for high-impact items.\n\nTask List:\n[Insert task list]`,
    category: 'Productivity',
    tags: ['eisenhower-matrix', 'time-management', 'prioritization'],
    description: 'Organizes tasks by urgency and importance to maximize daily focus.',
    createdAt: new Date(Date.now() - 21600000).toISOString(),
    updatedAt: new Date(Date.now() - 21600000).toISOString(),
    isFavorite: true,
    isPinned: false,
    order: 8,
  },
  {
    id: 'sample-10',
    title: 'System Prompt Architect for AI Agents',
    prompt: `Design a robust System Prompt for an AI Customer Support Agent. Define persona, tone of voice, explicit boundaries (what NOT to answer), output format JSON schema, and multi-turn fallback protocol for escalations.`,
    category: 'Others',
    tags: ['system-prompt', 'ai-agent', 'prompt-engineering'],
    description: 'Architects production-grade system prompts for LLM agents.',
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date(Date.now() - 3600000).toISOString(),
    isFavorite: false,
    isPinned: false,
    order: 9,
  },
];
